name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SPRING_FLYWAY_PASSWORD: ${{ secrets.SPRING_FLYWAY_PASSWORD }}
      SPRING_PROFILES_ACTIVE: test
      BASE64_PRIVATE_KEY: ${{ secrets.BASE64_PRIVATE_KEY }}
      PATH_PRIVATE_KEY: ${{ secrets.PATH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Create private key directory and file
        run: |
          mkdir -p $(dirname "$PATH_PRIVATE_KEY")
          echo "$BASE64_PRIVATE_KEY" | base64 --decode > "$PATH_PRIVATE_KEY"
        shell: bash

      - name: Build with Maven
        run: mvn -f service/pom.xml clean test
