name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up environment variables
        run: echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn -f service/pom.xml clean test
